version: "3.8"

services:
  php74:
    container_name: php74
    image: php-fpm:7.4.3
  dev-mysql:
    container_name: dev-mysql
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_ROOT_HOST: "%"

  dev-redis:
    container_name: dev-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  dev-es:
    container_name: dev-es
    image: elasticsearch:7.9.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver/data:/var/opt/mssql
    cap_add:
      - SYS_PTRACE
